# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

version: "3.7"

networks:
  fineract: {}

services:
  mysql:
    image: mysql:5.7
    # TODO: the migration scripts have to be fixed (syntax) for MySQL 8
    #image: mysql:8
    logging:
      driver: none
    volumes:
      - ./fineract-db/docker:/docker-entrypoint-initdb.d
      #- /tmp/fineract:/var/lib/mysql
    networks:
      - fineract
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      #- MYSQL_DATABASE=mifostenant-default
    ports:
      - "3306:3306"
    command: mysqld --sql_mode=""
  activemq:
    image: rmohr/activemq:5.15.9-alpine
    logging:
      driver: none
    volumes:
      - ./fineract-activemq/conf:/opt/activemq/conf
    networks:
      - fineract
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
      - "61613:61613"
      - "1883:1883"
      - "61614:61614"
  fineract:
    image: docker.pkg.github.com/fiter1/fineract-ng/fineract:latest
    environment:
      - FINERACT_SERVER_PORT=8443
      - FINERACT_DB_URL=jdbc:mysql://mysql:3306/mifostenant-default?useUnicode=true&characterEncoding=UTF-8
      - FINERACT_DB_USERNAME=root
      - FINERACT_DB_PASSWORD=mysql
      - FINERACT_DB_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - FINERACT_DB_INITIALIZE=false
      - FINERACT_DB_POOL_CONNECTION_TIMEOUT=20000
      - FINERACT_DB_POOL_MAX_SIZE=10
      - FINERACT_DB_POOL_MIN_IDLE=0
      - FINERACT_DB_POOL_MAX_LIFE=20000
      - FINERACT_DB_POOL_IGNORE_ERROR=false
      - FINERACT_JCACHE_PROVIDER=org.ehcache.jsr107.EhcacheCachingProvider
      - FINERACT_JCACHE_CONFIG=classpath:META-INF/spring/ehcache.xml
      - FINERACT_JMS_URL=tcp://activemq:61616
      - FINERACT_JMS_USERNAME=admin
      - FINERACT_JMS_PASSWORD=admin
      - FINERACT_JMS_SESSION_CACHE_SIZE=5
      - FINERACT_JMS_POOL_ENABLED=true
      - FINERACT_JMS_POOL_MAX_SIZE=50
      - FINERACT_SSL_ENABLED=true
      - FINERACT_SSL_KEYSTORE_TYPE=JKS
      - FINERACT_SSL_KEYSTORE_LOCATION=classpath:keystore.jks
      - FINERACT_SSL_KEYSTORE_PASSWORD=openmf
      - FINERACT_SSL_KEYSTORE_ALIAS=
      - FINERACT_TENANT_ID=default
      - FINERACT_TIMEZONE_ID=Europe/Belgrade
      # NOTE: careful! special characters like "$" have to be escaped "$$"; you have to provide your password Bcrypt encoded
      - FINERACT_APP_USER_PASSWORD=$$2a$$10$$djoMbaRGGRgqN9c/Z0.17eojfxLqcF8eMSHgpM/tGCewIQHA4Du66
      - FINERACT_CONNECTION_REMOVE_ABANDONED=true
      - FINERACT_CONNECTION_REMOVE_ABANDONED_TIMEOUT=60
      - FINERACT_CONNECTION_LOG_ABANDONED=true
      - FINERACT_CONNECTION_ABANDON_WHEN_PERCENTAGE_FULL=50
      - FINERACT_CONNECTION_MAX_ACTIVE=40
      - FINERACT_CONNECTION_MIN_IDLE=10
      - FINERACT_CONNECTION_MAX_IDLE=20
      - FINERACT_CONNECTION_SUSPECT_TIMEOUT=60
      - FINERACT_CONNECTION_TIME_BETWEEN_EVICTION_RUNS_MILLIS=34000
      - FINERACT_CONNECTION_MIN_EVICTABLE_IDLE_TIME_MILLIS=60000
      - FINERACT_CONNECTION_MAX_RETRIES_ON_DEADLOCK=0
      - FINERACT_CONNECTION_MAX_INTERVAL_BETWEEN_RETRIES=1
      - FINERACT_CORS_ALLOW_CREDENTIALS=true
      - FINERACT_CORS_ALLOWED_HEADERS=*
      - FINERACT_CORS_ALLOWED_METHODS=*
      - FINERACT_CORS_ALLOWED_ORIGINS=*
      - FINERACT_BASE_URL=/fineract-provider/api/v1
    networks:
      - fineract
    depends_on:
      - mysql
      - activemq
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8008:8008"
    command: sh -c "java -agentlib:jdwp=transport=dt_socket,server=y,address=*:8008,suspend=n -Xmx512m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Duser.timezone=UTC -Djava.net.preferIPv4Stack=true --illegal-access=permit --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED -jar fineract-provider*.jar --spring.profiles.active=default,basicauth"
