# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

version: "3.7"

volumes:
  data: {}

services:
  mysql:
    #image: mysql:5.7
    image: mysql:8
    volumes:
      - ./fineract-db/docker:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"

  activemq:
    image: rmohr/activemq:5.15.9-alpine
    logging:
      driver: none
    volumes:
      - ./fineract-activemq/conf:/opt/activemq/conf
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
      - "61613:61613"
      - "1883:1883"
      - "61614:61614"

  fineract:
    image: hub.docker.org/apache/fineract:latest
    depends_on:
      - mysql
      - activemq
    ports:
      - "8443:8443"
      - "8008:8008"
    command: sh -c "java -agentlib:jdwp=transport=dt_socket,server=y,address=*:8008,suspend=n -Xmx512m -Duser.timezone=UTC --illegal-access=permit --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED -jar -Djava.net.preferIPv4Stack=true fineract-provider-*.jar --spring.profiles.active=default,basicauth"
