name: Fineract develop Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: kamiazya/setup-graphviz@v1

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Build with Gradle
        # TODO: when everything is properly setup then we can use the full monty
        #run: ./gradlew clean build publish docker dockerTag dockerTagsPush -x test
        run: ./gradlew clean build -x test
        env:
          GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
          GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}