name: Fineract ibanera Build

on:
  push:
    branches:
      - frank/dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: kamiazya/setup-graphviz@v1

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Login to Github Packages Docker
        uses: azure/docker-login@v1
        with:
          login-server: 'docker.pkg.github.com'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build with Gradle
        run: ./gradlew clean build docker dockerPush -x test

      - name: Deploy to sandbox
        run: |
          echo "$DEMO_SSH_KEY" > key.pem
          chmod 400 key.pem

          echo "Restart docker container...!!!"
          ssh -i key.pem -o StrictHostKeyChecking=no $DEMO_URL '/root/deploy-fineract.sh'
        env:
          DEMO_SSH_KEY: ${{secrets.DEMO_SSH_KEY}}
          DEMO_URL: ${{secrets.DEMO_URL}}
